// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yard_Scan_API.Data.Context;

#nullable disable

namespace Yard_Scan_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221115151838_GetSubzoneUsagePercentageFunc")]
    partial class GetSubzoneUsagePercentageFunc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.SubZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Spaces")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<string>("subName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("SubZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A",
                            Spaces = 14,
                            Status = false,
                            ZoneId = 1,
                            subName = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "B",
                            Spaces = 14,
                            Status = false,
                            ZoneId = 1,
                            subName = ""
                        },
                        new
                        {
                            Id = 3,
                            Name = "C",
                            Spaces = 14,
                            Status = false,
                            ZoneId = 1,
                            subName = ""
                        },
                        new
                        {
                            Id = 4,
                            Name = "D",
                            Spaces = 19,
                            Status = false,
                            ZoneId = 1,
                            subName = ""
                        });
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Space")
                        .HasColumnType("int");

                    b.Property<int>("SubZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrackInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrackOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubZoneId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double>("UsagePercentage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("dbo.zone_usage_percentage([Id])");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C4",
                            Status = false,
                            UsagePercentage = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Corralito",
                            Status = false,
                            UsagePercentage = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yarda",
                            Status = false,
                            UsagePercentage = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Campañas",
                            Status = false,
                            UsagePercentage = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Avenida",
                            Status = false,
                            UsagePercentage = 0.0
                        });
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Views.InspectUnitView", b =>
                {
                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.ToView("unit_on_inspect");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Views.UnitOnYardView", b =>
                {
                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Space")
                        .HasColumnType("int");

                    b.Property<string>("SubZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrackInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrackOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToView("units_on_yard");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.SubZone", b =>
                {
                    b.HasOne("Yard_Scan_API.Data.Entities.Zone", "Zone")
                        .WithMany("SubZones")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.Unit", b =>
                {
                    b.HasOne("Yard_Scan_API.Data.Entities.SubZone", "SubZone")
                        .WithMany("Units")
                        .HasForeignKey("SubZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yard_Scan_API.Data.Entities.Zone", "Zone")
                        .WithMany("Units")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubZone");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.SubZone", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Yard_Scan_API.Data.Entities.Zone", b =>
                {
                    b.Navigation("SubZones");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
